//
//  Colors.swift
//  speakEZ (iOS)
//
//  Created by Carson O'Sullivan on 9/14/21.
//

import Foundation
import SwiftUI

extension Color {
//    static let oldPrimaryColor = Color(UIColor.systemIndigo)
    static let mainColor = Color("mainColor")
    static let mainColorInverse = Color("mainColorInverse")
    static let supportingColor = Color("secondaryColor")
    static let speakerPurple = Color("speakerPurple")
    static let speakerPink = Color("speakerPink")
    static let speakerBlue = Color("speakerBlue")
    static let aliceBlue = Color("aliceBlue")
    static let alloyOrange = Color("alloyOrange")
    static let arylideYellow = Color("arylideYellow")
    static let babyBlue = Color("babyBlue")
    static let blackCoral = Color("blackCoral")
    static let bleuDeFrance = Color("bleuDeFrance")
    static let blizzardBlue = Color("blizzardBlue")
    static let bloodRed = Color("bloodRed")
    static let blueBell = Color("blueBell")
    static let bluePigment = Color("bluePigment")
    static let brightMaroon = Color("brightMaroon")
    static let brinkPink = Color("brinkPink")
    static let burntSienna = Color("burntSienna")
    static let cafeAuLait = Color("cafeAuLait")
    static let cafeNoir = Color("cafeNoir")
    static let cambridgeBlue = Color("cambridgeBlue")
    static let caribbeanGreen = Color("caribbeanGreen")
    static let celadonGreen = Color("celadonGreen")
    static let charmPink = Color("charmPink")
    static let chinaRose = Color("chinaRose")
    static let chineseRed = Color("chineseRed")
    static let cornflowerBlue = Color("cornflowerBlue")
    static let cottonCandy = Color("cottonCandy")
    static let cyberGrape = Color("cyberGrape")
    static let darkTurqoise = Color("darkTurqoise")
    static let deepPurple = Color("deepPurple")
    static let dodgerBlue = Color("dodgerBlue")
    static let earthYellow = Color("earthYellow")
    static let etonBlue = Color("etonBlue")
    static let fireEngineRed = Color("fireEngineRed")
    static let flourescentBlue = Color("flourescentBlue")
    static let forestGreen = Color("forestGreen")
    static let frenchMauve = Color("frenchMauve")
    static let frenchSkyBlue = Color("frenchSkyBlue")
    static let greenSheen = Color("greenSheen")
    static let indigoDye = Color("indigoDye")
    static let ivory = Color("ivory")
    static let juneBud = Color("juneBud")
    static let khakiWeb = Color("khakiWeb")
    static let laurelGreen = Color("laurelGreen")
    static let lavenderBlue = Color("lavenderBlue")
    static let lavenderFloral = Color("lavenderFloral")
    static let lightCyan = Color("lightCyan")
    static let magentaDye = Color("magentaDye")
    static let magentaHaze = Color("magentaHaze")
    static let magentaProcess = Color("magentaProcess")
    static let mandarin = Color("mandarin")
    static let mangolia = Color("mangolia")
    static let maximumBluePurple = Color("maximumBluePurple")
    static let maximumGreenYellow = Color("maximumGreenYellow")
    static let maximumYellowRed = Color("maximumYellowRed")
    static let mediumPurple = Color("mediumPurple")
    static let mellowApricot = Color("mellowApricot")
    static let middleRed = Color("middleRed")
    static let mintGreen = Color("mintGreen")
    static let oldLavender = Color("oldLavender")
    static let orangePeel = Color("orangePeel")
    static let oxfordBlue = Color("oxfordBlue")
    static let peachPuff = Color("peachPuff")
    static let pearlyPurple = Color("pearlyPurple")
    static let periwinkleCrayola = Color("periwinkleCrayola")
    static let persianGreen = Color("persianGreen")
    static let plumWeb = Color("plumWeb")
    static let raisinBlack = Color("raisinBlack")
    static let rawSienna = Color("rawSienna")
    static let romanSilver = Color("romanSilver")
    static let roseEbony = Color("roseEbony")
    static let rosePink = Color("rosePink")
    static let russianViolet = Color("russianViolet")
    static let safetyYellow = Color("safetyYellow")
    static let sandyBrown = Color("sandyBrown")
    static let sizzlingRed = Color("sizzlingRed")
    static let skyBlueCrayola = Color("skyBlueCrayola")
    static let springGreen = Color("springGreen")
    static let tartOrange = Color("tartOrange")
    static let taupeGray = Color("taupeGray")
    static let tealBlue = Color("tealBlue")
    static let upForestGreen = Color("upForestGreen")
    static let vividSkyBlue = Color("vividSkyBlue")
}

extension UIColor {
    static let speakerPurpleUI = UIColor(named: "speakerPurple")!
    static let speakerPinkUI = UIColor(named: "speakerPink")!
}

extension UIColor {
    static let speakerPurple : UIColor? = UIColor(named: "speakerPurple")
    static let speakerPink : UIColor? = UIColor(named: "speakerPink")
}
